### ISSUE TITLE
About linters

### ISSUE THREAD

**Issue by ranska** [franckverrot/tictactoe-elm#1]
Are alignments produce by elm-format on
https://github.com/franckverrot/tictactoe-elm/blob/master/src/Model.elm#L8-L11

If yes it could be a nice add to explain in a teaching purpose how to configure it.

**Comment by franckverrot** [comment]
I don't use elm-format, I do it manually for now. Good idea though. I just tried building it but `elm-vim` doesn't seem to play nice with the binary name in any case (ie: `elm-format-0.18` instead of just `elm-format`)
